# Generated by Django 5.2.13 on 2026-04-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quete',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quete',
            name='competences_debloquees',
            field=models.ManyToManyField(blank=True, help_text='Compétences ajoutées automatiquement au profil quand cette quête est validée', related_name='quetes_associees', to='api.competence'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_formateur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercompetence',
            name='auto_debloquee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quete',
            name='difficulte',
            field=models.IntegerField(choices=[(1, 'Facile'), (2, 'Moyen'), (3, 'Difficile')], default=1),
        ),
        migrations.AlterField(
            model_name='quete',
            name='instructions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userquete',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userquete',
            name='soumission',
            field=models.TextField(blank=True),
        ),
    ]
