# Generated by Django 5.2.13 on 2026-04-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_competence_description_quete_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='filieres_cibles',
            field=models.JSONField(blank=True, default=list, help_text='Liste des filières pour lesquelles cette compétence est proposée. Vide = toutes.'),
        ),
        migrations.AddField(
            model_name='quete',
            name='filieres_cibles',
            field=models.JSONField(blank=True, default=list, help_text='Filières qui voient cette quête en priorité. Vide = toutes les filières.'),
        ),
        migrations.AddField(
            model_name='user',
            name='ecole',
            field=models.CharField(blank=True, help_text='Nom de votre école', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='filiere',
            field=models.CharField(choices=[('informatique', '💻 Informatique'), ('litterature', '📚 Littérature'), ('langues', '🌍 Langues'), ('mathematiques', '📐 Mathématiques'), ('sciences_physiques', '⚗️ Sciences Physiques'), ('sante', '🏥 Santé'), ('sciences_naturelles', '🌿 Sciences Naturelles'), ('autre', '🎯 Autre')], default='informatique', max_length=50),
        ),
        migrations.AddField(
            model_name='userquete',
            name='recommandee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='competence',
            name='categorie',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('devops', 'DevOps'), ('data', 'Data'), ('redaction', 'Rédaction'), ('langues', 'Langues'), ('sciences', 'Sciences'), ('sante', 'Santé'), ('maths', 'Mathématiques'), ('autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quete',
            name='competences_debloquees',
            field=models.ManyToManyField(blank=True, related_name='quetes_associees', to='api.competence'),
        ),
    ]
