# Generated by Django 5.2.13 on 2026-04-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_competence_filieres_cibles_quete_filieres_cibles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(default='France', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('icone', models.CharField(default='🎓', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ordre', 'label'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='filiere',
        ),
        migrations.AddField(
            model_name='user',
            name='filieres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='competence',
            name='filieres_cibles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='quete',
            name='filieres_cibles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='ecole',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
